// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mooch.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mooch.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260826220457_ActivityDogJoinTable")]
    partial class ActivityDogJoinTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Mooch.Api.Entities.Activities.Activity", b =>
                {
                    b.Property<Guid>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("activityID");

                    b.Property<Guid?>("ConnectedAccountID")
                        .HasColumnType("uuid")
                        .HasColumnName("connectedAccountID");

                    b.Property<DateTimeOffset>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdDateUTC");

                    b.Property<decimal>("DistanceMiles")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalActivityID")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("externalActivityID");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<Guid>("WalkerID")
                        .HasColumnType("uuid")
                        .HasColumnName("walkerID");

                    b.HasKey("ActivityID");

                    b.HasIndex("CreatedDateUtc");

                    b.HasIndex("ConnectedAccountID", "ExternalActivityID")
                        .IsUnique()
                        .HasFilter("\"connectedAccountID\" IS NOT NULL AND \"externalActivityID\" IS NOT NULL");

                    b.HasIndex("WalkerID", "StartedAtUtc");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("Mooch.Api.Entities.Activities.ActivityDog", b =>
                {
                    b.Property<Guid>("ActivityDogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("activityDogID");

                    b.Property<Guid>("ActivityID")
                        .HasColumnType("uuid")
                        .HasColumnName("activityID");

                    b.Property<DateTimeOffset>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdDateUTC");

                    b.Property<Guid>("DogID")
                        .HasColumnType("uuid")
                        .HasColumnName("dogID");

                    b.HasKey("ActivityDogID");

                    b.HasIndex("ActivityID");

                    b.HasIndex("DogID");

                    b.HasIndex("ActivityID", "DogID")
                        .IsUnique();

                    b.HasIndex("DogID", "CreatedDateUtc");

                    b.ToTable("activity_dogs", (string)null);
                });

            modelBuilder.Entity("Mooch.Api.Entities.Activities.ImportedActivity", b =>
                {
                    b.Property<Guid>("ImportedActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("importedActivityID");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("activityType");

                    b.Property<Guid>("ConnectedAccountID")
                        .HasColumnType("uuid")
                        .HasColumnName("connectedAccountID");

                    b.Property<DateTimeOffset>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdDateUTC");

                    b.Property<decimal>("DistanceMiles")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalActivityID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("externalActivityID");

                    b.Property<bool>("RequiresDogAssignment")
                        .HasColumnType("boolean")
                        .HasColumnName("requiresDogAssignment");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<Guid>("WalkerID")
                        .HasColumnType("uuid")
                        .HasColumnName("walkerID");

                    b.HasKey("ImportedActivityID");

                    b.HasIndex("ConnectedAccountID", "ExternalActivityID")
                        .IsUnique();

                    b.HasIndex("WalkerID", "StartedAtUtc");

                    b.ToTable("imported_activities", (string)null);
                });

            modelBuilder.Entity("Mooch.Api.Entities.Challenges.Challenge", b =>
                {
                    b.Property<Guid>("ChallengeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("challengeID");

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.HasKey("ChallengeID");

                    b.ToTable("challenges", null, t =>
                        {
                            t.HasCheckConstraint("CK_challenges_date_range", "\"EndsOn\" >= \"StartsOn\"");
                        });
                });

            modelBuilder.Entity("Mooch.Api.Entities.Challenges.ChallengeParticipant", b =>
                {
                    b.Property<Guid>("ChallengeParticipantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("challengeParticipantID");

                    b.Property<Guid>("ChallengeID")
                        .HasColumnType("uuid")
                        .HasColumnName("challengeID");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid")
                        .HasColumnName("userID");

                    b.HasKey("ChallengeParticipantID");

                    b.HasIndex("UserID");

                    b.HasIndex("ChallengeID", "UserID")
                        .IsUnique();

                    b.ToTable("challenge_participants", (string)null);
                });

            modelBuilder.Entity("Mooch.Api.Entities.Dogs.Dog", b =>
                {
                    b.Property<Guid>("DogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("dogID");

                    b.Property<string>("AvatarImage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Breed")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdDateUTC");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("WeightPounds")
                        .HasColumnType("numeric");

                    b.HasKey("DogID");

                    b.ToTable("dogs", (string)null);
                });

            modelBuilder.Entity("Mooch.Api.Entities.Dogs.DogOwnerInvite", b =>
                {
                    b.Property<Guid>("DogOwnerInviteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("dogOwnerInviteID");

                    b.Property<DateTimeOffset>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdDateUTC");

                    b.Property<Guid>("DogID")
                        .HasColumnType("uuid")
                        .HasColumnName("dogID");

                    b.Property<Guid>("InvitedByWalkerID")
                        .HasColumnType("uuid")
                        .HasColumnName("invitedByWalkerID");

                    b.Property<string>("InviteeEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("inviteeEmail");

                    b.Property<DateTimeOffset?>("RespondedDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("respondedDateUTC");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("DogOwnerInviteID");

                    b.HasIndex("DogID");

                    b.HasIndex("InvitedByWalkerID");

                    b.HasIndex("DogID", "InviteeEmail", "Status")
                        .HasDatabaseName("IX_dog_owner_invites_pending_email");

                    b.ToTable("dog_owner_invites", (string)null);
                });

            modelBuilder.Entity("Mooch.Api.Entities.Friendships.Friendship", b =>
                {
                    b.Property<Guid>("FriendshipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("friendshipID");

                    b.Property<Guid>("AddresseeUserID")
                        .HasColumnType("uuid")
                        .HasColumnName("addresseeUserID");

                    b.Property<DateTimeOffset>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdDateUTC");

                    b.Property<Guid>("RequesterUserID")
                        .HasColumnType("uuid")
                        .HasColumnName("requesterUserID");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("FriendshipID");

                    b.HasIndex("AddresseeUserID", "Status");

                    b.HasIndex("RequesterUserID", "AddresseeUserID")
                        .IsUnique();

                    b.ToTable("friendships", null, t =>
                        {
                            t.HasCheckConstraint("CK_friendships_distinct_users", "\"requesterUserID\" <> \"addresseeUserID\"");
                        });
                });

            modelBuilder.Entity("Mooch.Api.Entities.Integrations.ConnectedAccount", b =>
                {
                    b.Property<Guid>("ConnectedAccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("connectedAccountID");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("AccessTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdDateUTC");

                    b.Property<string>("ExternalUserID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("externalUserID");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid")
                        .HasColumnName("userID");

                    b.HasKey("ConnectedAccountID");

                    b.HasIndex("Provider", "ExternalUserID")
                        .IsUnique();

                    b.HasIndex("UserID", "Provider")
                        .IsUnique();

                    b.ToTable("connected_accounts", (string)null);
                });

            modelBuilder.Entity("Mooch.Api.Entities.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarImage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Mooch.Api.Entities.Walkers.Walker", b =>
                {
                    b.Property<Guid>("WalkerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("walkerID");

                    b.Property<string>("AvatarImage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdDateUTC");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid")
                        .HasColumnName("userID");

                    b.HasKey("WalkerID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("walkers", (string)null);
                });

            modelBuilder.Entity("Mooch.Api.Entities.Walkers.WalkerDog", b =>
                {
                    b.Property<Guid>("WalkerDogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("walkerDogID");

                    b.Property<DateTimeOffset>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdDateUTC");

                    b.Property<Guid>("DogID")
                        .HasColumnType("uuid")
                        .HasColumnName("dogID");

                    b.Property<bool>("IsPrimaryOwner")
                        .HasColumnType("boolean");

                    b.Property<Guid>("WalkerID")
                        .HasColumnType("uuid")
                        .HasColumnName("walkerID");

                    b.HasKey("WalkerDogID");

                    b.HasIndex("DogID")
                        .IsUnique()
                        .HasDatabaseName("IX_walker_dogs_primary_owner")
                        .HasFilter("\"IsPrimaryOwner\" = true");

                    b.HasIndex("WalkerID", "DogID")
                        .IsUnique();

                    b.ToTable("walker_dogs", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Mooch.Api.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Mooch.Api.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mooch.Api.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Mooch.Api.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mooch.Api.Entities.Activities.Activity", b =>
                {
                    b.HasOne("Mooch.Api.Entities.Integrations.ConnectedAccount", "ConnectedAccount")
                        .WithMany("Activities")
                        .HasForeignKey("ConnectedAccountID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mooch.Api.Entities.Walkers.Walker", "Walker")
                        .WithMany("Activities")
                        .HasForeignKey("WalkerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConnectedAccount");

                    b.Navigation("Walker");
                });

            modelBuilder.Entity("Mooch.Api.Entities.Activities.ActivityDog", b =>
                {
                    b.HasOne("Mooch.Api.Entities.Activities.Activity", "Activity")
                        .WithMany("ActivityDogs")
                        .HasForeignKey("ActivityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mooch.Api.Entities.Dogs.Dog", "Dog")
                        .WithMany("ActivityDogs")
                        .HasForeignKey("DogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Dog");
                });

            modelBuilder.Entity("Mooch.Api.Entities.Activities.ImportedActivity", b =>
                {
                    b.HasOne("Mooch.Api.Entities.Integrations.ConnectedAccount", "ConnectedAccount")
                        .WithMany()
                        .HasForeignKey("ConnectedAccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mooch.Api.Entities.Walkers.Walker", "Walker")
                        .WithMany()
                        .HasForeignKey("WalkerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectedAccount");

                    b.Navigation("Walker");
                });

            modelBuilder.Entity("Mooch.Api.Entities.Challenges.ChallengeParticipant", b =>
                {
                    b.HasOne("Mooch.Api.Entities.Challenges.Challenge", "Challenge")
                        .WithMany("Participants")
                        .HasForeignKey("ChallengeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mooch.Api.Entities.Users.AppUser", "User")
                        .WithMany("ChallengeParticipants")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mooch.Api.Entities.Dogs.DogOwnerInvite", b =>
                {
                    b.HasOne("Mooch.Api.Entities.Dogs.Dog", "Dog")
                        .WithMany("OwnerInvites")
                        .HasForeignKey("DogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mooch.Api.Entities.Walkers.Walker", "InvitedByWalker")
                        .WithMany("SentDogOwnerInvites")
                        .HasForeignKey("InvitedByWalkerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("InvitedByWalker");
                });

            modelBuilder.Entity("Mooch.Api.Entities.Friendships.Friendship", b =>
                {
                    b.HasOne("Mooch.Api.Entities.Users.AppUser", "Addressee")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("AddresseeUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mooch.Api.Entities.Users.AppUser", "Requester")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("RequesterUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Mooch.Api.Entities.Integrations.ConnectedAccount", b =>
                {
                    b.HasOne("Mooch.Api.Entities.Users.AppUser", "User")
                        .WithMany("ConnectedAccounts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mooch.Api.Entities.Walkers.Walker", b =>
                {
                    b.HasOne("Mooch.Api.Entities.Users.AppUser", "User")
                        .WithOne("Walker")
                        .HasForeignKey("Mooch.Api.Entities.Walkers.Walker", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mooch.Api.Entities.Walkers.WalkerDog", b =>
                {
                    b.HasOne("Mooch.Api.Entities.Dogs.Dog", "Dog")
                        .WithMany("WalkerDogs")
                        .HasForeignKey("DogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mooch.Api.Entities.Walkers.Walker", "Walker")
                        .WithMany("WalkerDogs")
                        .HasForeignKey("WalkerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("Walker");
                });

            modelBuilder.Entity("Mooch.Api.Entities.Activities.Activity", b =>
                {
                    b.Navigation("ActivityDogs");
                });

            modelBuilder.Entity("Mooch.Api.Entities.Challenges.Challenge", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Mooch.Api.Entities.Dogs.Dog", b =>
                {
                    b.Navigation("ActivityDogs");

                    b.Navigation("OwnerInvites");

                    b.Navigation("WalkerDogs");
                });

            modelBuilder.Entity("Mooch.Api.Entities.Integrations.ConnectedAccount", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Mooch.Api.Entities.Users.AppUser", b =>
                {
                    b.Navigation("ChallengeParticipants");

                    b.Navigation("ConnectedAccounts");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("Walker");
                });

            modelBuilder.Entity("Mooch.Api.Entities.Walkers.Walker", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("SentDogOwnerInvites");

                    b.Navigation("WalkerDogs");
                });
#pragma warning restore 612, 618
        }
    }
}
